#ifndef TPROXY2TUNNEL_UDP_PROXY_H
#define TPROXY2TUNNEL_UDP_PROXY_H

/* ── udp_proxy.h ───────────────────────────────────────────────────────────
 * Tunnel-mode UDP proxy types.
 * No SOCKS5 TCP control channel — sessions are immediately usable.
 * ──────────────────────────────────────────────────────────────────────── */

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "ev_types.h"

#include "lrucache.h"   /* myhash_hh, MYLRU_HASH_*, LRU_DEFINE_*  */
#include "netutils.h"   /* ip_port_t                           */

/* ════════════════════════════════════════════════════════════════════════
 * Cache Capacity API
 * ════════════════════════════════════════════════════════════════════════ */

uint16_t udp_lrucache_get_main_maxsize(void);
uint16_t udp_lrucache_get_fork_maxsize(void);
uint16_t udp_lrucache_get_tproxy_maxsize(void);
void udp_lrucache_set_maxsize(uint16_t base_size);

/* ════════════════════════════════════════════════════════════════════════
 * Memory-pool / queue constants
 * ════════════════════════════════════════════════════════════════════════ */

#define MEMPOOL_INITIAL_SIZE  256

#define UDP_BATCH_SIZE           16

#define MAX_DOMAIN_LEN        255

/* Maximum tunnel UDP header: ATYP(1) + LEN(1) + DOMAIN(255) + PORT(2) = 259 */
#define MAX_TUNNEL_UDP_HEADER 259

/* ════════════════════════════════════════════════════════════════════════
 * Cache key types
 * ════════════════════════════════════════════════════════════════════════ */

/*
 * udp_fork_key_t — composite key for the Fork Table.
 * Identifies a unique (client, target) pair for Symmetric NAT splitting.
 */
typedef struct {
    ip_port_t client_ipport;
    bool      target_is_ipv4;   /* protocol-family flag for target */
    ip_port_t target_ipport;    /* full address for Symmetric NAT  */
} udp_fork_key_t;

/* ════════════════════════════════════════════════════════════════════════
 * udp_tunnelctx_t — session context for the Main Table and Fork Table
 *
 * Tunnel mode: no TCP control channel, no handshake, no pending queue.
 * Session is immediately usable after UDP socket creation.
 * ════════════════════════════════════════════════════════════════════════ */

typedef struct {
    /* ── cache keys ────────────────────────────────── */
    ip_port_t      key_ipport;   /* Main Table key: client source IP:Port  */
    udp_fork_key_t fork_key;     /* Fork Table key: (client, target) pair  */

    /* ── session metadata ──────────────────────────── */
    ip_port_t      orig_dstaddr; /* original destination (FakeIP or real)  */
    bool           dest_is_ipv4; /* protocol-family flag for orig_dstaddr  */
    bool           is_forked;    /* true => entry lives in Fork Table      */
    bool           is_fakedns;   /* true => FakeDNS session                */

    /* ── libev watcher ─────────────────────────────── */
    evio_t    udp_watcher;  /* connected UDP socket to tunnel server      */

    /* ── GC timestamp ──────────────────────────────── */
    ev_tstamp last_active;

    /* ── uthash bookkeeping (must be last) ─────────── */
    myhash_hh hh;
} udp_tunnelctx_t;

/* ════════════════════════════════════════════════════════════════════════
 * udp_tproxyctx_t  — per-source-socket context for the TProxy Table
 * ════════════════════════════════════════════════════════════════════════ */

typedef struct {
    ip_port_t key_ipport;   /* (remote) source socket address */
    int       udp_sockfd;   /* bound to the above address      */
    ev_tstamp last_active;  /* GC timestamp */

    myhash_hh hh;           /* uthash bookkeeping              */
} udp_tproxyctx_t;

/* ════════════════════════════════════════════════════════════════════════
 * LRU cache function declarations
 * (bodies generated by LRU_DEFINE_* in udp_lrucache.c)
 * ════════════════════════════════════════════════════════════════════════ */

/* add — returns the evicted entry when over capacity, else NULL. */
udp_tunnelctx_t* udp_tunnelctx_add(udp_tunnelctx_t **cache, udp_tunnelctx_t *entry);
udp_tunnelctx_t* udp_tunnelctx_fork_add(udp_tunnelctx_t **cache, udp_tunnelctx_t *entry);
udp_tproxyctx_t* udp_tproxyctx_add(udp_tproxyctx_t **cache, udp_tproxyctx_t *entry);

/* find — pure lookup; returns NULL on miss */
udp_tunnelctx_t* udp_tunnelctx_find(udp_tunnelctx_t **cache, const ip_port_t      *keyptr);
udp_tunnelctx_t* udp_tunnelctx_fork_find(udp_tunnelctx_t **cache, const udp_fork_key_t *keyptr);
udp_tproxyctx_t* udp_tproxyctx_find(udp_tproxyctx_t **cache, const ip_port_t      *keyptr);

/* del — unconditional removal */
void udp_tunnelctx_del(udp_tunnelctx_t **cache, udp_tunnelctx_t *entry);
void udp_tproxyctx_del(udp_tproxyctx_t **cache, udp_tproxyctx_t *entry);

/* clear — iterate and invoke callback, safe for removal */
typedef void (*udp_tunnelctx_cb_t)(void *ctx, udp_tunnelctx_t *entry);
typedef void (*udp_tproxyctx_cb_t)(void *ctx, udp_tproxyctx_t *entry);

void udp_tunnelctx_clear_main(udp_tunnelctx_t **cache, udp_tunnelctx_cb_t cb, void *ctx);
void udp_tunnelctx_clear_fork(udp_tunnelctx_t **cache, udp_tunnelctx_cb_t cb, void *ctx);
void udp_tproxyctx_clear(udp_tproxyctx_t **cache, udp_tproxyctx_cb_t cb, void *ctx);

/* ════════════════════════════════════════════════════════════════════════
 * Event callbacks
 * ════════════════════════════════════════════════════════════════════════ */

void udp_tproxy_recvmsg_cb(evloop_t *evloop, struct ev_watcher *watcher, int revents);
void udp_proxy_close_all_sessions(evloop_t *evloop);
void udp_proxy_init_gc(evloop_t *evloop);
void udp_proxy_stop_gc(evloop_t *evloop);

#endif /* TPROXY2TUNNEL_UDP_PROXY_H */
